travis:
  secure:
    BINSTAR_TOKEN: H9jbnDknj8t5C2PmaBbM18r1uhjnHcbO471//N4sql04QAwSaB4X+T6eS3YWJyDfyJm/zctiPf70XeEON9FPLG7Yjhi4Lu77VAOoiZDqmrY26FF6RpFzV4TJM6FqUM6xV3B4kFeyk30Wdx8r58itwkugqPLvwSO4G1rEMz1VaNAcfMsIEDJl5sdlJh0egxR6KS3g1qj5qLUET2ubIRTYx+AtRJswfW4eT69V/uOZdpSFumexf90B6wmaoPQO7xxnQ4jrb/kp7UBvmvcbAYKjhYgyHTE9gpMlBEa5owSaRanBC1AHF38G/fjy105V+lE1pikF6GB69acE8hzT8r+uxpNayohy5Lww7mJ5ssJ57ZgK4k+ZOyIvLFTm9xytUP+41YEUrTA3Uwl3+SjynrNTlmzdvLOGhpjKKkH6TMqK5sn3Nqj2e66e+3VDz1B1f+d2s7s6n+Z+GuX50bXCo/cD7z53NaA8RU5b7WVaoM4qzm/3cPFCd8EZwGOi1f5iLPedlL/7gOfDtYjFL/gms2gtis6Ia4jYr+m2q1YG8Up/1YkXD309f7rT2Lbp9RAxZCG7JIUW6jmI5HgIkwdyGnjRZ6zV8I/rMfLtbATb0Mt194ovChtRPfzbo/H5TqYR3zdV5GC1nYC9tL60zwleRyBqRIngk4y7KqPvjAJel/9oBc0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
